# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vtenigin <vtenigin@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/03 18:36:51 by vtenigin          #+#    #+#              #
#    Updated: 2017/07/06 23:28:13 by vtenigin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = traps

FLAGS = -Wall -Wextra -Werror

SRC = SuperTrap.cpp NinjaTrap.cpp FragTrap.cpp ScavTrap.cpp ClapTrap.cpp main.cpp

all: $(NAME)

$(NAME):
	clang++ $(FLAGS) -o $(NAME) $(SRC)

fclean:
	rm -f $(NAME)

re: fclean all
